services:
  # A Streamlit web service
  - type: web
    name: maritime-port-digital-twin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && streamlit run integrated_app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
    autoDeploy: true
    healthCheckPath: /_stcore/health
    # A few useful environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false 